insert into MCU
VALUES
(1, "Iron Man", "Tony", "Stark", "Earth", "Hero"),
(17, "Iron Monger", "Obadiah", "Stane", "Earth", "Villian"),
(2, "The Incredible Hulk", "Robert", "Banner", "Earth", "Hero"),
(8, "Abomination", "Emil", "Blonsky", "Earth", "Villain"),
(9, "The Leader", "Samuel", "Sterns", "Earth", NULL),
(7, "War Machine", "James", "Rhodes", "Earth", "Hero"),
(3, "Black Widow", "Natasha", "Romanoff", "Earth","Hero"),
(10, "Justin Hammer", "Justin", "Hammer", "Earth", "Villain"),
(11, "Whiplash", "Ivan", "Vanko", "Earth", "Villain"), 
(4, "Thor", "Thor", "Odinson", "Asgard", "Hero"),
(12, "Loki", "Loki", "Laufeyson", "Jotunheim", "Antihero"),
(5, "Captain America", "Steven", "Rogers", "Earth", "Hero"),
(13, "Peggy Carter", "Margaret", "Carter", "Earth", "Hero"),
(14, "The Winter Soldier", "James", "Barnes", "Earth", "Hero"),
(15, "Red Skull", "Johann", "Schmidt", "Earth", "Villain"),
(16, "The Mandarin", "Aldrich", "Killian", "Earth", "Villain"),
(6, "Hawkeye", "Clint", "Barton", "Earth", "Hero"),
(18, "Malekith", "Malekith", NULL, "Svaltalfheim", "Villain"),
(19, "Falcon", "Sam", "Wilson", "Earth", "Hero"),
(20, "Director Fury", "Nicholas", "Fury", "Earth", "Hero"),
(21, "Agent Hill", "Maria", "Hill", "Earth", "Hero"),
(22, "Crossbones", "Brock", "Rumlow", "Earth", "Villain"),
(23, "Agent 13", "Sharon", "Carter", "Earth", "Hero"),
(24, "Secretary Pierce", "Alexander", "Pierce", "Earth", "Villain"),
(25, "Arnim Zola", "Arnim", "Zola", "Earth", "Villain"),
(26, "Star-Lord", "Peter", "Quill", "Earth", "Hero"),
(27, "Gamora", "Gamora", NULL, "Zen-Whoberi", "Hero"),
(28, "Rocket Raccoon", "Rocket", NULL, "Half-World", "Hero"),
(29, "Groot", "Groot", NULL, "Planet X", "Hero"),
(30, "Drax the Destroyer", "Drax", NULL, NULL, "Hero"),
(31, "Ronan the Accuser", "Ronan", NULL, "Hala", "Villain"),
(32, "Scarlet Witch", "Wanda", "Maximoff", "Earth", "Hero"),
(33, "Quicksilver", "Pietro", "Maximoff", "Earth", "Hero"),
(34, "Ultron", "Ultron", NULL, "Earth", "Hero"),
(35, "Vision", "Vision", NULL, "Earth", "Hero"),
(36, "Ant-Man", "Scott", "Lang", "Earth", "Hero"),
(37, "Wasp", "Hope", "van Dyne", "Earth", "Hero"),
(38, "Black Panther", "T'Challa", NULL, "Earth", "Hero"),
(39, "Spider-Man", "Peter", "Parker", "Earth", "Hero");